# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd46e19aaa0972a310b801fc5782af2815cb2a8334153dc5d1e6e818da80e5a0529bf8d8b8d8cccf594191c02bea5cfd1f4b53fee1b22e9cdbc13142ef747eaf

test:
  secret_key_base: a1347c73e45a6fbc9f9ea7d588a1ca4c81800253195d558052695d7df083c67101410f823a73aece8d50b25ea1611dddb624b3c4cd8fec1bec5ec188cfdf3625

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
